### ISSUE TITLE
yarn-container-logs not giving back any containers

### ISSUE THREAD

**Issue by zommerfelds** [hammerlab/yarn-logs-helpers#7] opened 2016-04-19 15:34 UTC
Hi, I'd love to use your tool, however, it seems like `yarn-container-logs` is not outputting any container logs at all. All the folders inside the created application ID folder are empty.

```
$ yarn-container-logs 0025
Downloading logs for application_1457471530597_0025 and splitting per-container...
/usr/hdp/2.4.0.0-169//hadoop-yarn/bin/yarn.distro: line 64: /localhome/hadoop/hadoop-2.6.0/libexec/yarn-config.sh: No such file or directory
Done downloading; rename and create per-host directories...
Removing: ./containers/container-
Look for driver containers and application masters...
grep: containers/container_*: No such file or directory
grep: containers/container_*: No such file or directory
Creating EID symlinks...
grep: containers/*: No such file or directory

$ ls application_1457471530597_0025/containers

```

**Comment by zommerfelds** [comment] 2016-04-19 15:36
Turns out that Bash is not configured properly on my cluster. I will see if I can get this resolved. Would be nice if these scripts would work with Zsh.

**Comment by zommerfelds** [comment] 2016-04-19 15:41
Got Bash working properly. The script still doesn't work:

```
$ yarn-container-logs 0025
Downloading logs for application_1457471530597_0025 and splitting per-container...
16/04/19 17:39:00 INFO impl.TimelineClientImpl: Timeline service address: http://xxxxxxxxxx:8188/ws/v1/timeline/
16/04/19 17:39:00 INFO client.RMProxy: Connecting to ResourceManager at iccluster075.iccluster.epfl.ch/10.90.39.26:8050
Unable to get ApplicationState. Attempting to fetch logs directly from the filesystem.
Done downloading; rename and create per-host directories...
Removing: ./containers/container-
Look for driver containers and application masters...
grep: containers/container_*: No such file or directory
grep: containers/container_*: No such file or directory
Creating EID symlinks...
grep: containers/*: No such file or directory
```

**Comment by zommerfelds** [comment] 2016-04-19 16:00
Please close the issue when you see this, as it is not very relevant. Are you interested if I make some additions to the scripts?

**Comment by ryan-williams** [comment] 2016-04-19 16:06
Hi @zommerfelds! Thanks for dropping in, as you've noticed these scripts are rough around the edges. Any additions you want to make are welcome. I'll add `set -e` to `yarn-container-logs` and document the `$PATH` addition as you mentioned.

**Comment by ryan-williams** [comment] 2016-04-19 16:06
Also, if you can describe more what went wrong with finding the cluster ID, that would be nice to get fixed as well

**Comment by ryan-williams** [comment] 2016-04-19 16:31
I [added `set -e`](https://github.com/hammerlab/yarn-logs-helpers/commit/5522556dbae31b9c78f3c97ad82051d4b27fa367), and [made the `.sourceme` file add the repo dir to `$PATH`](https://github.com/hammerlab/yarn-logs-helpers/commit/b4e89e1caf99cbac9ab095fff1194dccafc57f06) and [documented it on the README](https://github.com/hammerlab/yarn-logs-helpers/commit/5b1aa99c4c4216ad685df6a3695c3b52715a363f).

**Comment by zommerfelds** [comment] 2016-04-19 18:52
Thanks!
The reason for the ID being wrong is that for some reason there exist two different `application_XXXXXXXX` prefixes. I don't know where this ID comes from. An alternative would be to grep all the applications every time you run yarn-container-logs and try to mach it with the input.

**Comment by ryan-williams** [comment] 2016-04-19 18:56
Yea we could go through the YARN API but it is slow IME so it'd be nice to avoid that.

On my cluster, that prefix seems to be fixed for the life of the RM, and is updated only on RM restart. Is it possible you're looking at apps from different RM incarnations?

**Comment by zommerfelds** [comment] 2016-04-19 19:06
It is possible yeah, but I'm not sure, since I don't manage the cluster. The admins are currently setting up the cluster; it could be that they restarted it a few times in the beginning. Maybe we can change the ID to be the last match, rather than the first one.

**Comment by ryan-williams** [comment] 2016-04-19 19:21
gtk. My current disposition is that the 4-digit-abbreviation only working during the lifetime of one YARN RM process is "working as intended".

Whenever my RM is restarted I run `yarn-refresh-cluster-id` to get `~/.yarn-cluster-id` updated.

i'm not even sure otomh what to `grep` for the 4-digit argument in, to figure out which app the user might be referring to, across multiple RM incarnations; `yarn application -list` will only show apps from the current RM.

Passing the full app ID when it's from a previous RM seems like the right workaround.

**Comment by zommerfelds** [comment] 2016-04-19 19:27
Actually, if I run `yarn application -list -appStates ALL` I see different ID prefixes. Maybe they persisted across restarts or maybe the different IDs are not related to restarts.

BTW, this is not a big problem for me, my main use of the script right now is to split containers logs.

**Comment by ryan-williams** [comment] 2016-04-19 19:29
Great, sounds good, I'll close this then. Thanks for your help.

**Closed by ryan-williams** 2016-04-19 19:29 UTC
